/**
 * Comprehensive Mock Data Engine for CivicFix Admin Panel
 * Configured for Gandhidham Municipal Corporation (Kutch, Gujarat).
 * 
 * NOTE: For Hackathon demo only.
 * // TODO: Replace with real Appwrite database collections (issues, staff, audit_logs).
 */

import { AdminIssue, StaffMember, DepartmentName, AuditLogEntry } from '../../types/admin';

export const DEPARTMENTS: DepartmentName[] = [
  'Roads & Infrastructure',
  'Public Works & Electricity',
  'Water & Sewage',
  'Sanitation & Solid Waste',
  'Drainage & Flood Control',
];

export const INITIAL_MOCK_STAFF: StaffMember[] = [
  {
    id: 'stf-001',
    name: 'Rajesh Varma',
    email: 'rajesh.varma@civicfix.gov.in',
    department: 'Roads & Infrastructure',
    status: 'active',
    activeAssignedCount: 3,
    phone: '+91 98251 10001',
  },
  {
    id: 'stf-002',
    name: 'Priya Patel',
    email: 'priya.patel@civicfix.gov.in',
    department: 'Roads & Infrastructure',
    status: 'active',
    activeAssignedCount: 1,
    phone: '+91 98251 10002',
  },
  {
    id: 'stf-003',
    name: 'Vikram Joshi',
    email: 'vikram.joshi@civicfix.gov.in',
    department: 'Public Works & Electricity',
    status: 'active',
    activeAssignedCount: 2,
    phone: '+91 98251 10003',
  },
  {
    id: 'stf-004',
    name: 'Sneha Dave',
    email: 'sneha.dave@civicfix.gov.in',
    department: 'Public Works & Electricity',
    status: 'active',
    activeAssignedCount: 1,
    phone: '+91 98251 10004',
  },
  {
    id: 'stf-005',
    name: 'Amit Solanki',
    email: 'amit.solanki@civicfix.gov.in',
    department: 'Water & Sewage',
    status: 'active',
    activeAssignedCount: 2,
    phone: '+91 98251 10005',
  },
  {
    id: 'stf-006',
    name: 'Kavita Makwana',
    email: 'kavita.makwana@civicfix.gov.in',
    department: 'Water & Sewage',
    status: 'disabled',
    activeAssignedCount: 0,
    phone: '+91 98251 10006',
  },
  {
    id: 'stf-007',
    name: 'Dharmesh Ahir',
    email: 'dharmesh.ahir@civicfix.gov.in',
    department: 'Sanitation & Solid Waste',
    status: 'active',
    activeAssignedCount: 4,
    phone: '+91 98251 10007',
  },
  {
    id: 'stf-008',
    name: 'Mehul Gadhvi',
    email: 'mehul.gadhvi@civicfix.gov.in',
    department: 'Drainage & Flood Control',
    status: 'active',
    activeAssignedCount: 2,
    phone: '+91 98251 10008',
  },
];

// Realistic base timestamps
const NOW = Date.now();
const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

export const INITIAL_MOCK_ISSUES: AdminIssue[] = [
  {
    id: 'CF-2026-081',
    title: 'Severe road depression & pothole cluster',
    description: 'Deep road damage creating traffic snarls near Rotary Circle during evening rush hour.',
    category: 'Pothole',
    severity: 'High',
    department: 'Roads & Infrastructure',
    assignedStaffId: 'stf-001',
    assignedStaffName: 'Rajesh Varma',
    status: 'In Progress',
    createdDate: new Date(NOW - 5 * HOUR).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 5 * HOUR,
    slaDeadline: new Date(NOW + 19 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW + 19 * HOUR,
    isSlaBreached: false,
    isEscalated: false,
    flagged: { isFlagged: false },
    ward: 'Ward 4 (Central)',
    locationName: 'Rotary Circle, Main Highway Junction',
    latitude: 23.0792,
    longitude: 70.1345,
    votes: 42,
  },
  {
    id: 'CF-2026-079',
    title: 'High-mast streetlight flickering off continuously',
    description: 'Multiple streetlights non-operational, dark blind spot at pedestrian crossing.',
    category: 'Streetlight',
    severity: 'Medium',
    department: 'Public Works & Electricity',
    assignedStaffId: null,
    assignedStaffName: null,
    status: 'Reported',
    createdDate: new Date(NOW - 1 * HOUR).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 1 * HOUR,
    slaDeadline: new Date(NOW + 23 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW + 23 * HOUR,
    isSlaBreached: false,
    isEscalated: false,
    flagged: { isFlagged: false },
    ward: 'Ward 2 (North)',
    locationName: 'Tagore Road, Opp. Town Hall',
    latitude: 23.0825,
    longitude: 70.131,
    votes: 19,
  },
  {
    id: 'CF-2026-074',
    title: 'Main pipeline water leakage spilling onto highway',
    description: 'Fresh water gushing into road shoulder, causing localized water-logging and loss.',
    category: 'Water Leakage',
    severity: 'Critical',
    department: 'Water & Sewage',
    assignedStaffId: 'stf-005',
    assignedStaffName: 'Amit Solanki',
    status: 'Acknowledged',
    createdDate: new Date(NOW - 2 * DAY).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 2 * DAY,
    slaDeadline: new Date(NOW - 14 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW - 14 * HOUR,
    isSlaBreached: true,
    isEscalated: true,
    escalationReason: 'SLA breached (+14 hrs). Critical pipeline rupture requires heavy excavation equipment.',
    flagged: { isFlagged: false },
    ward: 'Ward 1 (West)',
    locationName: 'Sector 1A, Near Community Center',
    latitude: 23.0738,
    longitude: 70.1265,
    votes: 31,
  },
  {
    id: 'CF-2026-068',
    title: 'Commercial waste bin overflow in market lane',
    description: 'Uncollected organic and plastic debris spilled across pedestrian walkway.',
    category: 'Garbage',
    severity: 'Medium',
    department: 'Sanitation & Solid Waste',
    assignedStaffId: 'stf-007',
    assignedStaffName: 'Dharmesh Ahir',
    status: 'Resolved',
    createdDate: new Date(NOW - 3 * DAY).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 3 * DAY,
    slaDeadline: new Date(NOW - 1 * DAY).toISOString(),
    slaDeadlineTimestamp: NOW - 1 * DAY,
    isSlaBreached: false,
    isEscalated: false,
    flagged: { isFlagged: false },
    ward: 'Ward 3 (East)',
    locationName: 'Oslo Circle Market Lane',
    latitude: 23.085,
    longitude: 70.141,
    votes: 56,
  },
  {
    id: 'CF-2026-063',
    title: 'Storm drain blockage before monsoon outlet',
    description: 'Silt and construction debris clogging culvert opening next to railway crossing.',
    category: 'Drainage',
    severity: 'High',
    department: 'Drainage & Flood Control',
    assignedStaffId: 'stf-008',
    assignedStaffName: 'Mehul Gadhvi',
    status: 'In Progress',
    createdDate: new Date(NOW - 3 * DAY).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 3 * DAY,
    slaDeadline: new Date(NOW - 22 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW - 22 * HOUR,
    isSlaBreached: true,
    isEscalated: true,
    escalationReason: 'Staff requested urgent excavator assistance due to heavy sediment hardening.',
    flagged: { isFlagged: false },
    ward: 'Ward 5 (South)',
    locationName: 'Railway Colony Road',
    latitude: 23.0695,
    longitude: 70.138,
    votes: 27,
  },
  {
    id: 'CF-2026-059',
    title: 'Damaged storm drain concrete cover slab',
    description: 'Concrete slab shattered, hazardous hole for two-wheelers and pedestrians.',
    category: 'Drainage',
    severity: 'Critical',
    department: 'Drainage & Flood Control',
    assignedStaffId: 'stf-008',
    assignedStaffName: 'Mehul Gadhvi',
    status: 'Resolved',
    createdDate: new Date(NOW - 4 * DAY).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 4 * DAY,
    slaDeadline: new Date(NOW - 2 * DAY).toISOString(),
    slaDeadlineTimestamp: NOW - 2 * DAY,
    isSlaBreached: false,
    isEscalated: false,
    flagged: { isFlagged: false },
    ward: 'Ward 6 (Industrial)',
    locationName: 'GIDC Industrial Phase 1',
    latitude: 23.076,
    longitude: 70.145,
    votes: 64,
  },
  // Pre-seeded Flagged Issue: Duplicate
  {
    id: 'CF-2026-092',
    title: 'Pothole on highway near Rotary Circle',
    description: 'Citizen reported another pothole right beside the rotary circle junction.',
    category: 'Pothole',
    severity: 'Medium',
    department: 'Roads & Infrastructure',
    assignedStaffId: 'stf-001',
    assignedStaffName: 'Rajesh Varma',
    status: 'Acknowledged',
    createdDate: new Date(NOW - 4 * HOUR).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 4 * HOUR,
    slaDeadline: new Date(NOW + 20 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW + 20 * HOUR,
    isSlaBreached: false,
    isEscalated: false,
    flagged: {
      isFlagged: true,
      type: 'duplicate',
      reason: 'Duplicate of active work order CF-2026-081 reported within 10 meters at Rotary Circle.',
      flaggedByStaffId: 'stf-001',
      flaggedByStaffName: 'Rajesh Varma',
      flaggedAt: new Date(NOW - 2 * HOUR).toISOString(),
    },
    ward: 'Ward 4 (Central)',
    locationName: 'Rotary Circle, Main Highway Junction',
    latitude: 23.0794,
    longitude: 70.1347,
    votes: 5,
  },
  // Pre-seeded Flagged Issue: Invalid / Spam
  {
    id: 'CF-2026-095',
    title: 'Broken boundary wall inside private bungalow',
    description: 'Requesting municipality to repair garden wall damaged during private renovation.',
    category: 'Other',
    severity: 'Low',
    department: 'Public Works & Electricity',
    assignedStaffId: 'stf-003',
    assignedStaffName: 'Vikram Joshi',
    status: 'Reported',
    createdDate: new Date(NOW - 6 * HOUR).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 6 * HOUR,
    slaDeadline: new Date(NOW + 18 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW + 18 * HOUR,
    isSlaBreached: false,
    isEscalated: false,
    flagged: {
      isFlagged: true,
      type: 'invalid',
      reason: 'Private residential property boundary. Outside municipal jurisdiction and public asset scope.',
      flaggedByStaffId: 'stf-003',
      flaggedByStaffName: 'Vikram Joshi',
      flaggedAt: new Date(NOW - 3 * HOUR).toISOString(),
    },
    ward: 'Ward 1 (West)',
    locationName: 'Plot 42, Private Society, Sector 1A',
    latitude: 23.0715,
    longitude: 70.1245,
    votes: 1,
  },
  // Additional varied issues for system-wide overview
  {
    id: 'CF-2026-101',
    title: 'Exposed high-voltage underground cable splice',
    description: 'Electric cable exposed following road widening work, posing electrocution hazard.',
    category: 'Streetlight',
    severity: 'Critical',
    department: 'Public Works & Electricity',
    assignedStaffId: 'stf-004',
    assignedStaffName: 'Sneha Dave',
    status: 'In Progress',
    createdDate: new Date(NOW - 8 * HOUR).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 8 * HOUR,
    slaDeadline: new Date(NOW + 4 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW + 4 * HOUR,
    isSlaBreached: false,
    isEscalated: false,
    flagged: { isFlagged: false },
    ward: 'Ward 2 (North)',
    locationName: 'Sector 5, Near Substation',
    latitude: 23.084,
    longitude: 70.133,
    votes: 38,
  },
  {
    id: 'CF-2026-104',
    title: 'Open sanitary manhole without warning barricade',
    description: 'Cast iron cover stolen overnight; deep drop danger on busy school route.',
    category: 'Water Leakage',
    severity: 'Critical',
    department: 'Water & Sewage',
    assignedStaffId: null,
    assignedStaffName: null,
    status: 'Reported',
    createdDate: new Date(NOW - 2 * HOUR).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 2 * HOUR,
    slaDeadline: new Date(NOW + 10 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW + 10 * HOUR,
    isSlaBreached: false,
    isEscalated: true,
    escalationReason: 'Immediate danger to school bus traffic. Unassigned emergency.',
    flagged: { isFlagged: false },
    ward: 'Ward 3 (East)',
    locationName: 'School Road, Opp. St. Xavier Gate',
    latitude: 23.087,
    longitude: 70.143,
    votes: 52,
  },
  {
    id: 'CF-2026-108',
    title: 'Hospital perimeter biomedical waste dumping',
    description: 'Uncovered medical packaging and organic waste dumped behind community health clinic.',
    category: 'Garbage',
    severity: 'High',
    department: 'Sanitation & Solid Waste',
    assignedStaffId: 'stf-007',
    assignedStaffName: 'Dharmesh Ahir',
    status: 'In Progress',
    createdDate: new Date(NOW - 18 * HOUR).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 18 * HOUR,
    slaDeadline: new Date(NOW + 6 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW + 6 * HOUR,
    isSlaBreached: false,
    isEscalated: false,
    flagged: { isFlagged: false },
    ward: 'Ward 4 (Central)',
    locationName: 'Civil Hospital Road',
    latitude: 23.081,
    longitude: 70.137,
    votes: 29,
  },
  {
    id: 'CF-2026-112',
    title: 'Asphalt crumbling along newly paved sector connector',
    description: 'Premature surface breakdown and loose gravel causing skidding for two-wheelers.',
    category: 'Pothole',
    severity: 'Low',
    department: 'Roads & Infrastructure',
    assignedStaffId: 'stf-002',
    assignedStaffName: 'Priya Patel',
    status: 'Reported',
    createdDate: new Date(NOW - 1 * DAY).toISOString().split('T')[0],
    createdAtTimestamp: NOW - 1 * DAY,
    slaDeadline: new Date(NOW + 48 * HOUR).toISOString(),
    slaDeadlineTimestamp: NOW + 48 * HOUR,
    isSlaBreached: false,
    isEscalated: false,
    flagged: { isFlagged: false },
    ward: 'Ward 6 (Industrial)',
    locationName: 'Connector Road 3, GIDC',
    latitude: 23.078,
    longitude: 70.148,
    votes: 8,
  },
];

export const INITIAL_MOCK_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'log-101',
    timestamp: new Date(NOW - 2 * HOUR).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
    timestampMs: NOW - 2 * HOUR,
    actorId: 'stf-001',
    actorName: 'Rajesh Varma (Staff)',
    action: 'FLAG_DUPLICATE',
    details: 'Flagged issue CF-2026-092 as duplicate of CF-2026-081',
    issueId: 'CF-2026-092',
  },
  {
    id: 'log-102',
    timestamp: new Date(NOW - 3 * HOUR).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
    timestampMs: NOW - 3 * HOUR,
    actorId: 'stf-003',
    actorName: 'Vikram Joshi (Staff)',
    action: 'FLAG_INVALID',
    details: 'Flagged issue CF-2026-095 as outside municipal public jurisdiction',
    issueId: 'CF-2026-095',
  },
  {
    id: 'log-103',
    timestamp: new Date(NOW - 5 * HOUR).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
    timestampMs: NOW - 5 * HOUR,
    actorId: 'adm-001',
    actorName: 'Super Admin (Municipality)',
    action: 'ASSIGN_ISSUE',
    details: 'Assigned CF-2026-081 to Rajesh Varma in Roads & Infrastructure',
    issueId: 'CF-2026-081',
  },
  {
    id: 'log-104',
    timestamp: new Date(NOW - 14 * HOUR).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
    timestampMs: NOW - 14 * HOUR,
    actorId: 'sys-sla',
    actorName: 'System SLA Monitor',
    action: 'SLA_BREACH_DETECTED',
    details: 'SLA deadline exceeded for CF-2026-074 (+14 hrs). Placed into Escalation Queue.',
    issueId: 'CF-2026-074',
  },
  {
    id: 'log-105',
    timestamp: new Date(NOW - 1 * DAY).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
    timestampMs: NOW - 1 * DAY,
    actorId: 'adm-001',
    actorName: 'Super Admin (Municipality)',
    action: 'STATUS_UPDATE',
    details: 'Marked issue CF-2026-068 as Resolved with clean pickup confirmation',
    issueId: 'CF-2026-068',
  },
];
